export type RootStackParamList = {
  Home: undefined;
  WhipUrl: undefined;
  Publisher: {whipUrl: string};
  WhepUrl: undefined;
  Player: {whepUrl: string};
  HlsUrl: undefined;
  HlsPlayer: {hlsUrl: string};
  SrtUrl: undefined;
  SrtPlayer: {srtUrl: string};
  DashUrl: undefined;
  DashPlayer: {dashUrl: string};
  RtmpUrl: undefined;
  RtmpPlayer: {rtmpUrl: string};
  RtmpPublishUrl: undefined;
  RtmpPublisher: {rtmpUrl: string};
  FlvUrl: undefined;
  FlvPlayer: {flvUrl: string};
  TsUrl: undefined;
  TsPlayer: {tsUrl: string};
};
